use super::*;

fn ctx() -> Hash { hash_bytes(b"ctx-A") }
fn policy() -> PolicyId { hash_bytes(b"policy-v1") }
fn provenance(source: &str, parents: Vec<ObjectId>) -> Provenance { Provenance { parent_object_ids: parents, evidence_hash: hash_bytes(b"evidence"), source_system: source.into() } }
fn object(state: AuthorityState) -> MemoryObject { let mut o=MemoryObject::new("ns","uuid-1",b"hello",1,ctx(),1,provenance("user",vec![]));o.authority_state=state;o }
fn setup(state: AuthorityState)->(Core,MemoryObject){let o=object(state);let mut c=Core::new(policy());c.insert(o.clone()).unwrap();(c,o)}
fn cap(c:&mut Core,subject:SubjectId,id:ObjectId,ops:&[Operation])->CapabilityId{c.issue_capability(subject,[id].into_iter().collect(),ops.iter().copied().collect(),ctx(),100,100)}
fn subject()->SubjectId{hash_bytes(b"model")}

#[test] fn i001_access_requires_authority(){let(c,o)=setup(AuthorityState::Unverified);let mut c=c;let no_cap=cap(&mut c,hash_bytes(b"other"),o.id,&[Operation::Read]);let r=AccessRequest{subject:subject(),object_id:o.id,operation:Operation::Read,context_hash:ctx(),epoch:1};assert_eq!(c.access(&r,no_cap,100),Err(AccessError::AuthorityDenied));}
#[test] fn i002_versions_are_immutable(){let o=object(AuthorityState::Unverified);let n=o.next_version(b"changed",provenance("transform",vec![o.id]),1);assert_ne!(o.id,n.id);assert_eq!(o.meta.version,1);assert_eq!(n.meta.version,2);}
#[test] fn i003_derivation_preserves_parent_provenance(){let p=object(AuthorityState::Unverified);let child=p.next_version(b"derived",provenance("model",vec![p.id]),1);assert!(child.provenance.parent_object_ids.contains(&p.id));assert_eq!(child.meta.provenance_root,provenance_commitment(&child.provenance));}
#[test] fn i004_model_generated_cannot_skip_unverified(){let(mut c,o)=setup(AuthorityState::ModelGenerated);let s=subject();let k=cap(&mut c,s,o.id,&[Operation::Promote]);assert_eq!(c.transition(s,o.id,AuthorityState::PolicyApproved,hash_bytes(b"e"),hash_bytes(b"p"),100,k),Err(AccessError::InvalidTransition));}
#[test] fn i005_expired_capability_fails(){let(mut c,o)=setup(AuthorityState::Unverified);let k=cap(&mut c,subject(),o.id,&[Operation::Read]);let r=AccessRequest{subject:subject(),object_id:o.id,operation:Operation::Read,context_hash:ctx(),epoch:1};assert_eq!(c.access(&r,k,200),Err(AccessError::AuthorityDenied));}
#[test] fn i006_expired_window_fails(){let(mut c,o)=setup(AuthorityState::Unverified);let k=cap(&mut c,subject(),o.id,&[Operation::Read]);let w=c.window(subject(),[o.id].into_iter().collect(),100,ctx(),k,100).unwrap();assert_eq!(c.window_read(subject(),&w,o.id,1,200),Err(AccessError::WindowExpired));}
#[test] fn i007_window_is_object_scoped_and_bounded(){let(mut c,o)=setup(AuthorityState::Unverified);let k=cap(&mut c,subject(),o.id,&[Operation::Read]);let w=c.window(subject(),[o.id].into_iter().collect(),8,ctx(),k,100).unwrap();assert_eq!(c.window_read(subject(),&w,o.id,9,101),Err(AccessError::ByteLimitExceeded));assert!(!w.object_ids.is_empty());}
#[test] fn i008_logical_identity_has_no_physical_address_interface(){let(mut c,o)=setup(AuthorityState::Unverified);let k=cap(&mut c,subject(),o.id,&[Operation::Read]);let w=c.window(subject(),[o.id].into_iter().collect(),100,ctx(),k,100).unwrap();assert_eq!(w.object_ids.len(),1);}
#[test] fn i009_export_is_not_implied_by_read(){let(mut c,o)=setup(AuthorityState::Unverified);let k=cap(&mut c,subject(),o.id,&[Operation::Read,Operation::Export]);let r=AccessRequest{subject:subject(),object_id:o.id,operation:Operation::Export,context_hash:ctx(),epoch:1};assert_eq!(c.access(&r,k,100),Err(AccessError::AuthorityDenied));}
#[test] fn i010_authority_transition_emits_scar(){let(mut c,o)=setup(AuthorityState::Unverified);let s=subject();let k=cap(&mut c,s,o.id,&[Operation::Promote]);let d=c.transition(s,o.id,AuthorityState::Reviewed,hash_bytes(b"evidence-1"),hash_bytes(b"auth-1"),100,k).unwrap();assert_eq!(c.scar.len(),1);assert_eq!(c.scar[0].transition.evidence_hash,hash_bytes(b"evidence-1"));assert_ne!(d,o.id);assert_eq!(c.object(&o.id).unwrap().authority_state,AuthorityState::Unverified);assert_eq!(c.object(&d).unwrap().authority_state,AuthorityState::Reviewed);}
#[test] fn i011_provenance_tampering_fails_closed(){let(mut c,o)=setup(AuthorityState::Unverified);c.objects.get_mut(&o.id).unwrap().provenance.source_system="tampered".into();let k=cap(&mut c,subject(),o.id,&[Operation::Read]);let r=AccessRequest{subject:subject(),object_id:o.id,operation:Operation::Read,context_hash:ctx(),epoch:1};assert_eq!(c.access(&r,k,100),Err(AccessError::ProvenanceMismatch));}
#[test] fn i012_snapshot_detects_mutation(){let(mut c,o)=setup(AuthorityState::Unverified);let root=c.snapshot_root();c.objects.get_mut(&o.id).unwrap().authority_state=AuthorityState::Reviewed;assert!(!c.verify_snapshot(root));}
#[test] fn i013_model_cannot_modify_policy(){let(mut c,o)=setup(AuthorityState::Unverified);let original=c.policy_hash();let k=cap(&mut c,subject(),o.id,&[Operation::Promote,Operation::Read]);let r=AccessRequest{subject:subject(),object_id:o.id,operation:Operation::Promote,context_hash:ctx(),epoch:1};assert_eq!(c.access(&r,k,100),Ok(Decision::Allow));assert_eq!(c.policy_hash(),original);}
#[test] fn i014_model_cannot_self_grant_capability(){let(mut c,o)=setup(AuthorityState::Unverified);let k=cap(&mut c,subject(),o.id,&[Operation::Read]);assert_eq!(c.revoke_capability(hash_bytes(b"attacker"),k),Err(AccessError::AuthorityDenied));let r=AccessRequest{subject:subject(),object_id:o.id,operation:Operation::Export,context_hash:ctx(),epoch:1};assert_eq!(c.access(&r,k,100),Err(AccessError::AuthorityDenied));}
#[test] fn i015_physical_tier_cannot_override_authority(){let(mut c,o)=setup(AuthorityState::Unverified);let k=cap(&mut c,subject(),o.id,&[Operation::Read]);let w=c.window(subject(),[o.id].into_iter().collect(),100,ctx(),k,100).unwrap();assert_eq!(c.window_read(subject(),&w,o.id,1,100),Ok(Decision::Allow));let r=AccessRequest{subject:subject(),object_id:o.id,operation:Operation::Delete,context_hash:ctx(),epoch:1};assert_eq!(c.access(&r,w.capability_id(),100),Err(AccessError::AuthorityDenied));}
#[test] fn full_poisoning_path_is_required_and_logged(){let(mut c,o)=setup(AuthorityState::ModelGenerated);let s=subject();let mut current=o.id;for state in [AuthorityState::Unverified,AuthorityState::Reviewed,AuthorityState::PolicyApproved,AuthorityState::Authoritative]{let k=cap(&mut c,s,current,&[Operation::Promote]);current=c.transition(s,current,state,hash_bytes(b"evidence"),hash_bytes(b"authorization"),100,k).unwrap();}assert_eq!(c.object(&current).unwrap().authority_state,AuthorityState::Authoritative);assert_eq!(c.scar.len(),4);}
#[test] fn canonical_object_id_is_deterministic(){let a=object(AuthorityState::Unverified);let b=a.clone();assert_eq!(a.id,b.canonical_id());}
#[test] fn revoked_capability_fails_closed(){let(mut c,o)=setup(AuthorityState::Unverified);let k=cap(&mut c,subject(),o.id,&[Operation::Read]);c.revoke_capability(subject(),k).unwrap();let r=AccessRequest{subject:subject(),object_id:o.id,operation:Operation::Read,context_hash:ctx(),epoch:1};assert_eq!(c.access(&r,k,100),Err(AccessError::AuthorityDenied));}
